CREATE TABLE IF NOT EXISTS request_log (
    id VARCHAR(32) PRIMARY KEY,
    city VARCHAR(32) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(7) NOT NULL,
    source VARCHAR(16) NOT NULL,
    error LONGTEXT NULL
);